
// Autogenerated
// -------------
// gulpfile.ts/wasm.ts --> generateBuildInfo

export const Build = {
    version: "0.72.0 (5f4c001adb907384a82d9150da507a39)",
    buildSeed: 1633675312480,
    "wdosbox.wasm": {
        "size": 9959361,
        "gzSize": 3120277
    },
    "wdosbox.js": {
        "size": 360891,
        "gzSize": 77050
    },
    "wlibzip.wasm": {
        "size": 849867,
        "gzSize": 273211
    },
    "wlibzip.js": {
        "size": 252587,
        "gzSize": 54640
    }
,
};
