
// Autogenerated
// -------------
// gulpfile.ts/wasm.ts --> generateBuildInfo

export const Build = {
    version: "0.72.3 (d176be7f510d27e01bc805d74d8c99e0)",
    buildSeed: 1645098320632,
    "wdosbox.wasm": {
        "size": 1475852,
        "gzSize": 499076
    },
    "wdosbox.js": {
        "size": 125344,
        "gzSize": 32406
    },
    "wlibzip.wasm": {
        "size": 112624,
        "gzSize": 54379
    },
    "wlibzip.js": {
        "size": 78794,
        "gzSize": 20391
    }
,
};
